FROM openjdk

ENV dburl 127.0.0.1:5432/tp_devops
ENV dbname tp_devops
ENV dbpwd tp_devops

EXPOSE 8080

ADD tp-docker-1.0.0.jar /

ENTRYPOINT java -Ddatabase.url=${dburl} -Ddatabase.usernamer=${dbname} -Ddatabase.password=${dbpwd} -jar tp-docker-1.0.0.jar